basePath: /
definitions:
  domain.AddPerson:
    properties:
      name:
        example: my_name
        type: string
      phone:
        example: my_phone
        type: string
      reason:
        example: my_reason
        type: string
      uploader:
        example: admin
        type: string
    type: object
  domain.Id:
    properties:
      id:
        example: 1
        type: integer
    type: object
  domain.Person:
    properties:
      id:
        example: 1
        type: integer
      name:
        example: my_name
        type: string
      phone:
        example: my_phone
        type: string
      reason:
        example: my_reason
        type: string
      time:
        example: 16.04.2023
        type: string
      uploader:
        example: admin
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: daniil13.spiridonov@yandex.ru
    name: Daniil56
  description: Swagger API for Golang Project Blacklist
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Blacklist
  version: "1.0"
paths:
  /:
    delete:
      consumes:
      - application/json
      description: remove a user from the blacklist
      parameters:
      - description: User ID
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/domain.Id'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: remove from blacklist
    get:
      consumes:
      - application/json
      description: search and get users from the blacklist by phone number or name
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: phone
        in: query
        name: phone
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Person'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: blacklisted search
    post:
      consumes:
      - application/json
      description: the method adds the user to the blacklist
      parameters:
      - description: Name, phone, reason and uploader
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/domain.AddPerson'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: add to blacklist
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
